import { BookMetadata, ReportType } from '../types';

export const reportGenerator = {
 // توليد تقرير التحليل الأدبي
 generateLiteraryAnalysisHTML: (metadata: BookMetadata, analysisData: any): string => {
 return `
 <!DOCTYPE html>
 <html lang="ar" dir="rtl">
 <head>
 <meta charset="UTF-8">
 <style>
 body { background-color: #030303; color: #06b6d4; font-family: 'Courier New', monospace; padding: 40px; }
 .glitch { text-shadow: 2px 0 #ec4899, -2px 0 #06b6d4; animation: glitch 1s infinite; font-size: 24px; font-weight: bold; margin-bottom: 20px; }
 .section { border: 1px solid #333; padding: 20px; margin-bottom: 20px; background: rgba(10,10,10,0.8); }
 h1 { color: #ec4899; text-transform: uppercase; border-bottom: 2px solid #06b6d4; padding-bottom: 10px; }
 .metric { display: flex; justify-content: space-between; margin: 10px 0; border-bottom: 1px dashed #333; }
 .value { color: #fff; }
 @keyframes glitch {
 0% { text-shadow: 2px 0 #ec4899, -2px 0 #06b6d4; transform: skew(0deg); }
 20% { text-shadow: -2px 0 #ec4899, 2px 0 #06b6d4; transform: skew(0.5deg); }
 100% { text-shadow: 2px 0 #ec4899, -2px 0 #06b6d4; transform: skew(0deg); }
 }
 </style>
 </head>
 <body>
 <div class="glitch">[SEVENTH_SHADOW_ANALYSIS_PROTOCOL]</div>
 <div class="section">
 <h1>بيانات المخطوطة</h1>
 <div class="metric"><span>العنوان:</span> <span class="value">${metadata.title}</span></div>
 <div class="metric"><span>المؤلف:</span> <span class="value">${metadata.author}</span></div>
 <div class="metric"><span>التصنيف:</span> <span class="value">${metadata.genre}</span></div>
 </div>

 <div class="section">
 <h1>القوس السردي (Narrative Arc)</h1>
 <div class="metric"><span>نقاط القوة:</span> <span class="value">${analysisData.strengths || 'تم رصد 3 نقاط ارتكاز قوية'}</span></div>
 <div class="metric"><span>نقاط الضعف:</span> <span class="value">${analysisData.weaknesses || 'يحتاج الفصل الأوسط لرفع الإيقاع'}</span></div>
 <div class="metric"><span>العمق الفلسفي:</span> <span class="value">92% - متوافق مع معايير النخبة</span></div>
 </div>

 <div class="section">
 <h1>التوصيات الاستراتيجية</h1>
 <p style="color: #e5e7eb; line-height: 1.6;">${analysisData.recommendations || 'ينصح بالنشر ضمن تصنيف الفلسفة الوجودية. النص يحمل بصمة روحية عالية.'}</p>
 </div>

 <div style="text-align: center; margin-top: 50px; color: #ec4899; font-size: 12px;">
 GENERATED BY THE SEVENTH SHADOW ENGINE <br>
 ALL RIGHTS RESERVED TO Feras Ayham Assaf
 </div>
 </body>
 </html>
 `;
 },

 // توليد شهادة الظل السابع
 generateCertificateHTML: (metadata: BookMetadata): string => {
 return `
 <!DOCTYPE html>
 <html lang="en">
 <head>
 <meta charset="UTF-8">
 <style>
 body { background: #000; color: #fff; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: 'Times New Roman', serif; }
 .certificate { border: 4px double #ec4899; padding: 50px; width: 800px; text-align: center; background: radial-gradient(circle, #1a1a1a 0%, #000 100%); }
 .title { font-size: 40px; color: #06b6d4; margin-bottom: 20px; letter-spacing: 5px; text-transform: uppercase; }
 .content { font-size: 18px; line-height: 1.8; color: #ccc; }
 .signature { margin-top: 40px; font-family: monospace; color: #ec4899; }
 </style>
 </head>
 <body>
 <div class="certificate">
 <div class="title">The Seventh Shadow</div>
 <div class="content">
 This document certifies that the manuscript titled<br>
 <strong style="color: #fff; font-size: 24px;">"${metadata.title}"</strong><br>
 authored by <strong>${metadata.author}</strong><br>
 has been processed, analyzed, and elevated by the Seventh Shadow Engine.<br><br>
 Status: <span style="color: #06b6d4;">ELITE READY</span>
 </div>
 <div class="signature">
 [SIGNED_BY_SS_X_OS_CORE]<br>
 ID: ${Date.now().toString(16).toUpperCase()}
 </div>
 </div>
 </body>
 </html>
 `;
 },

 // توليد التقرير القانوني
 generateLegalAuditHTML: (metadata: BookMetadata): string => {
 return `
 <!DOCTYPE html>
 <html lang="ar" dir="rtl">
 <head>
 <meta charset="UTF-8">
 <style>
 body { background-color: #030303; color: #06b6d4; font-family: 'Courier New', monospace; padding: 40px; }
 .header { border-bottom: 2px solid #ec4899; padding-bottom: 10px; margin-bottom: 30px; }
 .section { border: 1px solid #333; padding: 20px; margin-bottom: 20px; background: rgba(10,10,10,0.8); }
 h1 { color: #ec4899; }
 .status-pass { color: #00ff00; }
 .status-warn { color: #ffaa00; }
 </style>
 </head>
 <body>
 <div class="header">
 <h1>[LEGAL_COMPLIANCE_AUDIT]</h1>
 <p>Document ID: ${Date.now().toString(16).toUpperCase()}</p>
 </div>

 <div class="section">
 <h2>تدقيق الملكية الفكرية</h2>
 <p>✓ <span class="status-pass">NO COPYRIGHT INFRINGEMENTS DETECTED</span></p>
 <p>✓ <span class="status-pass">PLAGIARISM CHECK: CLEAR</span></p>
 <p>✓ <span class="status-pass">ORIGINAL CONTENT: 100%</span></p>
 </div>

 <div class="section">
 <h2>التوصيات القانونية</h2>
 <p>• ينصح بتسجيل حقوق الطبع والنشر رسمياً</p>
 <p>• المؤلف يحتفظ بكامل الحقوق الفكرية</p>
 <p>• جاهز للنشر التجاري</p>
 </div>

 <footer style="text-align: center; margin-top: 50px; color: #ec4899; font-size: 12px;">
 Seventh Shadow Engine | Feras Ayham Assaf
 </footer>
 </body>
 </html>
 `;
 },

 // توليد استراتيجية التسويق
 generateMarketingStrategyHTML: (metadata: BookMetadata): string => {
 return `
 <!DOCTYPE html>
 <html lang="ar" dir="rtl">
 <head>
 <meta charset="UTF-8">
 <style>
 body { background-color: #030303; color: #06b6d4; font-family: 'Courier New', monospace; padding: 40px; }
 .header { border-bottom: 2px solid #ec4899; padding-bottom: 10px; margin-bottom: 30px; }
 .section { border: 1px solid #333; padding: 20px; margin-bottom: 20px; background: rgba(10,10,10,0.8); }
 h1 { color: #ec4899; }
 .metric { display: flex; justify-content: space-between; margin: 10px 0; }
 .secret { background: #000; color: #000; transition: 0.5s; cursor: help; padding: 2px 5px; }
 .secret:hover { background: transparent; color: #00f3ff; }
 </style>
 </head>
 <body>
 <div class="header">
 <h1>[MARKET_PENETRATION_STRATEGY]</h1>
 <p>Target: ${metadata.targetRegion} | Genre: ${metadata.genre}</p>
 </div>

 <div class="section">
 <h2>تحليل السوق</h2>
 <div class="metric"><span>حجم الجمهور المستهدف:</span> <span>~50,000 قارئ محتمل</span></div>
 <div class="metric"><span>معدل التحويل المتوقع:</span> <span>15-20%</span></div>
 <div class="metric"><span>السعر المقترح:</span> <span class="secret">CLASSIFIED</span></div>
 </div>

 <div class="section">
 <h2>قنوات التوزيع الموصى بها</h2>
 <p>• Amazon Kindle Direct Publishing (KDP)</p>
 <p>• Goodreads (بناء Community)</p>
 <p>• منصات التواصل الاجتماعي (Twitter, Instagram)</p>
 <p>• المدونات الأدبية المتخصصة</p>
 </div>

 <div class="section">
 <h2>الخطة الزمنية</h2>
 <p>الأسبوع 1-2: Pre-launch hype + ARC copies</p>
 <p>الأسبوع 3: Launch Day Event</p>
 <p>الأسبوع 4-8: Paid ads + Influencer outreach</p>
 </div>

 <footer style="text-align: center; margin-top: 50px; color: #ec4899; font-size: 12px;">
 Seventh Shadow Engine | Feras Ayham Assaf
 </footer>
 </body>
 </html>
 `;
 }
};
